// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
	"database/sql"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    source_id, project_id, source_file_id, external_id, parent_external_id,
    title, started_at, ended_at, message_count, is_subagent, raw_path
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, source_id, project_id, source_file_id, external_id, parent_external_id, title, started_at, ended_at, message_count, is_subagent, raw_path
`

type CreateConversationParams struct {
	SourceID         int64          `json:"source_id"`
	ProjectID        sql.NullInt64  `json:"project_id"`
	SourceFileID     sql.NullInt64  `json:"source_file_id"`
	ExternalID       string         `json:"external_id"`
	ParentExternalID sql.NullString `json:"parent_external_id"`
	Title            sql.NullString `json:"title"`
	StartedAt        sql.NullString `json:"started_at"`
	EndedAt          sql.NullString `json:"ended_at"`
	MessageCount     int64          `json:"message_count"`
	IsSubagent       int64          `json:"is_subagent"`
	RawPath          string         `json:"raw_path"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.SourceID,
		arg.ProjectID,
		arg.SourceFileID,
		arg.ExternalID,
		arg.ParentExternalID,
		arg.Title,
		arg.StartedAt,
		arg.EndedAt,
		arg.MessageCount,
		arg.IsSubagent,
		arg.RawPath,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProjectID,
		&i.SourceFileID,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.MessageCount,
		&i.IsSubagent,
		&i.RawPath,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    conversation_id, source_file_id, role, seq, created_at, text, raw_json, raw_line, content_hash
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, conversation_id, source_file_id, role, seq, created_at, text, raw_json, raw_line, content_hash
`

type CreateMessageParams struct {
	ConversationID int64          `json:"conversation_id"`
	SourceFileID   sql.NullInt64  `json:"source_file_id"`
	Role           string         `json:"role"`
	Seq            int64          `json:"seq"`
	CreatedAt      sql.NullString `json:"created_at"`
	Text           sql.NullString `json:"text"`
	RawJson        string         `json:"raw_json"`
	RawLine        sql.NullInt64  `json:"raw_line"`
	ContentHash    string         `json:"content_hash"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ConversationID,
		arg.SourceFileID,
		arg.Role,
		arg.Seq,
		arg.CreatedAt,
		arg.Text,
		arg.RawJson,
		arg.RawLine,
		arg.ContentHash,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SourceFileID,
		&i.Role,
		&i.Seq,
		&i.CreatedAt,
		&i.Text,
		&i.RawJson,
		&i.RawLine,
		&i.ContentHash,
	)
	return i, err
}

const createMessageBlock = `-- name: CreateMessageBlock :one
INSERT INTO message_blocks (message_id, seq, type, text, raw_json)
VALUES (?, ?, ?, ?, ?)
RETURNING id, message_id, seq, type, text, raw_json
`

type CreateMessageBlockParams struct {
	MessageID int64          `json:"message_id"`
	Seq       int64          `json:"seq"`
	Type      string         `json:"type"`
	Text      sql.NullString `json:"text"`
	RawJson   sql.NullString `json:"raw_json"`
}

func (q *Queries) CreateMessageBlock(ctx context.Context, arg CreateMessageBlockParams) (MessageBlock, error) {
	row := q.db.QueryRowContext(ctx, createMessageBlock,
		arg.MessageID,
		arg.Seq,
		arg.Type,
		arg.Text,
		arg.RawJson,
	)
	var i MessageBlock
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Seq,
		&i.Type,
		&i.Text,
		&i.RawJson,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const deleteMessageBlock = `-- name: DeleteMessageBlock :exec
DELETE FROM message_blocks
WHERE id = ?
`

func (q *Queries) DeleteMessageBlock(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMessageBlock, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, source_id, project_id, source_file_id, external_id, parent_external_id, title, started_at, ended_at, message_count, is_subagent, raw_path FROM conversations
WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProjectID,
		&i.SourceFileID,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.MessageCount,
		&i.IsSubagent,
		&i.RawPath,
	)
	return i, err
}

const getConversationByExternalID = `-- name: GetConversationByExternalID :one
SELECT id, source_id, project_id, source_file_id, external_id, parent_external_id, title, started_at, ended_at, message_count, is_subagent, raw_path FROM conversations
WHERE source_id = ? AND external_id = ?
`

type GetConversationByExternalIDParams struct {
	SourceID   int64  `json:"source_id"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetConversationByExternalID(ctx context.Context, arg GetConversationByExternalIDParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByExternalID, arg.SourceID, arg.ExternalID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProjectID,
		&i.SourceFileID,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.MessageCount,
		&i.IsSubagent,
		&i.RawPath,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, source_file_id, role, seq, created_at, text, raw_json, raw_line, content_hash FROM messages
WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SourceFileID,
		&i.Role,
		&i.Seq,
		&i.CreatedAt,
		&i.Text,
		&i.RawJson,
		&i.RawLine,
		&i.ContentHash,
	)
	return i, err
}

const getMessageByRawLine = `-- name: GetMessageByRawLine :one
SELECT id, conversation_id, source_file_id, role, seq, created_at, text, raw_json, raw_line, content_hash FROM messages
WHERE source_file_id = ? AND raw_line = ?
`

type GetMessageByRawLineParams struct {
	SourceFileID sql.NullInt64 `json:"source_file_id"`
	RawLine      sql.NullInt64 `json:"raw_line"`
}

func (q *Queries) GetMessageByRawLine(ctx context.Context, arg GetMessageByRawLineParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByRawLine, arg.SourceFileID, arg.RawLine)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SourceFileID,
		&i.Role,
		&i.Seq,
		&i.CreatedAt,
		&i.Text,
		&i.RawJson,
		&i.RawLine,
		&i.ContentHash,
	)
	return i, err
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT id, conversation_id, source_file_id, role, seq, created_at, text, raw_json, raw_line, content_hash FROM messages
WHERE conversation_id = ?
ORDER BY seq
`

func (q *Queries) ListConversationMessages(ctx context.Context, conversationID int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SourceFileID,
			&i.Role,
			&i.Seq,
			&i.CreatedAt,
			&i.Text,
			&i.RawJson,
			&i.RawLine,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, source_id, project_id, source_file_id, external_id, parent_external_id, title, started_at, ended_at, message_count, is_subagent, raw_path FROM conversations
ORDER BY coalesce(started_at, ended_at) DESC, id DESC
LIMIT ? OFFSET ?
`

type ListConversationsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ProjectID,
			&i.SourceFileID,
			&i.ExternalID,
			&i.ParentExternalID,
			&i.Title,
			&i.StartedAt,
			&i.EndedAt,
			&i.MessageCount,
			&i.IsSubagent,
			&i.RawPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageBlocks = `-- name: ListMessageBlocks :many
SELECT id, message_id, seq, type, text, raw_json FROM message_blocks
WHERE message_id = ?
ORDER BY seq
`

func (q *Queries) ListMessageBlocks(ctx context.Context, messageID int64) ([]MessageBlock, error) {
	rows, err := q.db.QueryContext(ctx, listMessageBlocks, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageBlock{}
	for rows.Next() {
		var i MessageBlock
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Seq,
			&i.Type,
			&i.Text,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectConversations = `-- name: ListProjectConversations :many
SELECT id, source_id, project_id, source_file_id, external_id, parent_external_id, title, started_at, ended_at, message_count, is_subagent, raw_path FROM conversations
WHERE project_id = ?
ORDER BY coalesce(started_at, ended_at) DESC, id DESC
LIMIT ? OFFSET ?
`

type ListProjectConversationsParams struct {
	ProjectID sql.NullInt64 `json:"project_id"`
	Limit     int64         `json:"limit"`
	Offset    int64         `json:"offset"`
}

func (q *Queries) ListProjectConversations(ctx context.Context, arg ListProjectConversationsParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listProjectConversations, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ProjectID,
			&i.SourceFileID,
			&i.ExternalID,
			&i.ParentExternalID,
			&i.Title,
			&i.StartedAt,
			&i.EndedAt,
			&i.MessageCount,
			&i.IsSubagent,
			&i.RawPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConversation = `-- name: UpsertConversation :one
INSERT INTO conversations (
    source_id, project_id, source_file_id, external_id, parent_external_id,
    title, started_at, ended_at, message_count, is_subagent, raw_path
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(source_id, external_id) DO UPDATE SET
    project_id = excluded.project_id,
    source_file_id = excluded.source_file_id,
    parent_external_id = excluded.parent_external_id,
    title = excluded.title,
    started_at = excluded.started_at,
    ended_at = excluded.ended_at,
    message_count = excluded.message_count,
    is_subagent = excluded.is_subagent,
    raw_path = excluded.raw_path
RETURNING id, source_id, project_id, source_file_id, external_id, parent_external_id, title, started_at, ended_at, message_count, is_subagent, raw_path
`

type UpsertConversationParams struct {
	SourceID         int64          `json:"source_id"`
	ProjectID        sql.NullInt64  `json:"project_id"`
	SourceFileID     sql.NullInt64  `json:"source_file_id"`
	ExternalID       string         `json:"external_id"`
	ParentExternalID sql.NullString `json:"parent_external_id"`
	Title            sql.NullString `json:"title"`
	StartedAt        sql.NullString `json:"started_at"`
	EndedAt          sql.NullString `json:"ended_at"`
	MessageCount     int64          `json:"message_count"`
	IsSubagent       int64          `json:"is_subagent"`
	RawPath          string         `json:"raw_path"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, upsertConversation,
		arg.SourceID,
		arg.ProjectID,
		arg.SourceFileID,
		arg.ExternalID,
		arg.ParentExternalID,
		arg.Title,
		arg.StartedAt,
		arg.EndedAt,
		arg.MessageCount,
		arg.IsSubagent,
		arg.RawPath,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProjectID,
		&i.SourceFileID,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.MessageCount,
		&i.IsSubagent,
		&i.RawPath,
	)
	return i, err
}

const upsertMessage = `-- name: UpsertMessage :one
INSERT INTO messages (
    conversation_id, source_file_id, role, seq, created_at, text, raw_json, raw_line, content_hash
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(conversation_id, seq) DO UPDATE SET
    source_file_id = excluded.source_file_id,
    role = excluded.role,
    created_at = excluded.created_at,
    text = excluded.text,
    raw_json = excluded.raw_json,
    raw_line = excluded.raw_line,
    content_hash = excluded.content_hash
RETURNING id, conversation_id, source_file_id, role, seq, created_at, text, raw_json, raw_line, content_hash
`

type UpsertMessageParams struct {
	ConversationID int64          `json:"conversation_id"`
	SourceFileID   sql.NullInt64  `json:"source_file_id"`
	Role           string         `json:"role"`
	Seq            int64          `json:"seq"`
	CreatedAt      sql.NullString `json:"created_at"`
	Text           sql.NullString `json:"text"`
	RawJson        string         `json:"raw_json"`
	RawLine        sql.NullInt64  `json:"raw_line"`
	ContentHash    string         `json:"content_hash"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, upsertMessage,
		arg.ConversationID,
		arg.SourceFileID,
		arg.Role,
		arg.Seq,
		arg.CreatedAt,
		arg.Text,
		arg.RawJson,
		arg.RawLine,
		arg.ContentHash,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SourceFileID,
		&i.Role,
		&i.Seq,
		&i.CreatedAt,
		&i.Text,
		&i.RawJson,
		&i.RawLine,
		&i.ContentHash,
	)
	return i, err
}

const upsertMessageBlock = `-- name: UpsertMessageBlock :one
INSERT INTO message_blocks (message_id, seq, type, text, raw_json)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(message_id, seq) DO UPDATE SET
    type = excluded.type,
    text = excluded.text,
    raw_json = excluded.raw_json
RETURNING id, message_id, seq, type, text, raw_json
`

type UpsertMessageBlockParams struct {
	MessageID int64          `json:"message_id"`
	Seq       int64          `json:"seq"`
	Type      string         `json:"type"`
	Text      sql.NullString `json:"text"`
	RawJson   sql.NullString `json:"raw_json"`
}

func (q *Queries) UpsertMessageBlock(ctx context.Context, arg UpsertMessageBlockParams) (MessageBlock, error) {
	row := q.db.QueryRowContext(ctx, upsertMessageBlock,
		arg.MessageID,
		arg.Seq,
		arg.Type,
		arg.Text,
		arg.RawJson,
	)
	var i MessageBlock
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Seq,
		&i.Type,
		&i.Text,
		&i.RawJson,
	)
	return i, err
}
