// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (source_file_id, conversation_id, path, kind, text, sha256, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, source_file_id, conversation_id, path, kind, text, sha256, created_at
`

type CreateArtifactParams struct {
	SourceFileID   sql.NullInt64  `json:"source_file_id"`
	ConversationID sql.NullInt64  `json:"conversation_id"`
	Path           string         `json:"path"`
	Kind           string         `json:"kind"`
	Text           sql.NullString `json:"text"`
	Sha256         sql.NullString `json:"sha256"`
	CreatedAt      sql.NullString `json:"created_at"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.SourceFileID,
		arg.ConversationID,
		arg.Path,
		arg.Kind,
		arg.Text,
		arg.Sha256,
		arg.CreatedAt,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.SourceFileID,
		&i.ConversationID,
		&i.Path,
		&i.Kind,
		&i.Text,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const createFileMention = `-- name: CreateFileMention :one
INSERT INTO file_mentions (
    file_id, message_id, tool_call_id, mention_kind, line_start, line_end, snippet
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, file_id, message_id, tool_call_id, mention_kind, line_start, line_end, snippet
`

type CreateFileMentionParams struct {
	FileID      int64          `json:"file_id"`
	MessageID   sql.NullInt64  `json:"message_id"`
	ToolCallID  sql.NullInt64  `json:"tool_call_id"`
	MentionKind string         `json:"mention_kind"`
	LineStart   sql.NullInt64  `json:"line_start"`
	LineEnd     sql.NullInt64  `json:"line_end"`
	Snippet     sql.NullString `json:"snippet"`
}

func (q *Queries) CreateFileMention(ctx context.Context, arg CreateFileMentionParams) (FileMention, error) {
	row := q.db.QueryRowContext(ctx, createFileMention,
		arg.FileID,
		arg.MessageID,
		arg.ToolCallID,
		arg.MentionKind,
		arg.LineStart,
		arg.LineEnd,
		arg.Snippet,
	)
	var i FileMention
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.MessageID,
		&i.ToolCallID,
		&i.MentionKind,
		&i.LineStart,
		&i.LineEnd,
		&i.Snippet,
	)
	return i, err
}

const createPatch = `-- name: CreatePatch :one
INSERT INTO patches (
    tool_call_id, message_id, file_id, patch_kind, raw_patch,
    added_lines, removed_lines, parsed_ok
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, tool_call_id, message_id, file_id, patch_kind, raw_patch, added_lines, removed_lines, parsed_ok
`

type CreatePatchParams struct {
	ToolCallID   sql.NullInt64 `json:"tool_call_id"`
	MessageID    sql.NullInt64 `json:"message_id"`
	FileID       sql.NullInt64 `json:"file_id"`
	PatchKind    string        `json:"patch_kind"`
	RawPatch     string        `json:"raw_patch"`
	AddedLines   sql.NullInt64 `json:"added_lines"`
	RemovedLines sql.NullInt64 `json:"removed_lines"`
	ParsedOk     int64         `json:"parsed_ok"`
}

func (q *Queries) CreatePatch(ctx context.Context, arg CreatePatchParams) (Patch, error) {
	row := q.db.QueryRowContext(ctx, createPatch,
		arg.ToolCallID,
		arg.MessageID,
		arg.FileID,
		arg.PatchKind,
		arg.RawPatch,
		arg.AddedLines,
		arg.RemovedLines,
		arg.ParsedOk,
	)
	var i Patch
	err := row.Scan(
		&i.ID,
		&i.ToolCallID,
		&i.MessageID,
		&i.FileID,
		&i.PatchKind,
		&i.RawPatch,
		&i.AddedLines,
		&i.RemovedLines,
		&i.ParsedOk,
	)
	return i, err
}

const createToolCall = `-- name: CreateToolCall :one
INSERT INTO tool_calls (
    message_id, block_id, tool_name, arguments_json, working_directory,
    status, output_artifact_id, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, message_id, block_id, tool_name, arguments_json, working_directory, status, output_artifact_id, created_at
`

type CreateToolCallParams struct {
	MessageID        int64          `json:"message_id"`
	BlockID          sql.NullInt64  `json:"block_id"`
	ToolName         string         `json:"tool_name"`
	ArgumentsJson    sql.NullString `json:"arguments_json"`
	WorkingDirectory sql.NullString `json:"working_directory"`
	Status           sql.NullString `json:"status"`
	OutputArtifactID sql.NullInt64  `json:"output_artifact_id"`
	CreatedAt        sql.NullString `json:"created_at"`
}

func (q *Queries) CreateToolCall(ctx context.Context, arg CreateToolCallParams) (ToolCall, error) {
	row := q.db.QueryRowContext(ctx, createToolCall,
		arg.MessageID,
		arg.BlockID,
		arg.ToolName,
		arg.ArgumentsJson,
		arg.WorkingDirectory,
		arg.Status,
		arg.OutputArtifactID,
		arg.CreatedAt,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.BlockID,
		&i.ToolName,
		&i.ArgumentsJson,
		&i.WorkingDirectory,
		&i.Status,
		&i.OutputArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts
WHERE id = ?
`

func (q *Queries) DeleteArtifact(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArtifact, id)
	return err
}

const deleteFileMention = `-- name: DeleteFileMention :exec
DELETE FROM file_mentions
WHERE id = ?
`

func (q *Queries) DeleteFileMention(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFileMention, id)
	return err
}

const deleteFileMentionsForMessage = `-- name: DeleteFileMentionsForMessage :exec
DELETE FROM file_mentions
WHERE message_id = ?
`

func (q *Queries) DeleteFileMentionsForMessage(ctx context.Context, messageID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteFileMentionsForMessage, messageID)
	return err
}

const deletePatch = `-- name: DeletePatch :exec
DELETE FROM patches
WHERE id = ?
`

func (q *Queries) DeletePatch(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePatch, id)
	return err
}

const deleteToolCall = `-- name: DeleteToolCall :exec
DELETE FROM tool_calls
WHERE id = ?
`

func (q *Queries) DeleteToolCall(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteToolCall, id)
	return err
}

const deleteToolCallFileMentionsForMessage = `-- name: DeleteToolCallFileMentionsForMessage :exec
DELETE FROM file_mentions
WHERE tool_call_id IN (
    SELECT tc.id FROM tool_calls tc WHERE tc.message_id = ?
)
`

func (q *Queries) DeleteToolCallFileMentionsForMessage(ctx context.Context, messageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteToolCallFileMentionsForMessage, messageID)
	return err
}

const deleteToolCallsForMessage = `-- name: DeleteToolCallsForMessage :exec
DELETE FROM tool_calls
WHERE message_id = ?
`

func (q *Queries) DeleteToolCallsForMessage(ctx context.Context, messageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteToolCallsForMessage, messageID)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, source_file_id, conversation_id, path, kind, text, sha256, created_at FROM artifacts
WHERE id = ?
`

func (q *Queries) GetArtifact(ctx context.Context, id int64) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.SourceFileID,
		&i.ConversationID,
		&i.Path,
		&i.Kind,
		&i.Text,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const getToolCall = `-- name: GetToolCall :one
SELECT id, message_id, block_id, tool_name, arguments_json, working_directory, status, output_artifact_id, created_at FROM tool_calls
WHERE id = ?
`

func (q *Queries) GetToolCall(ctx context.Context, id int64) (ToolCall, error) {
	row := q.db.QueryRowContext(ctx, getToolCall, id)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.BlockID,
		&i.ToolName,
		&i.ArgumentsJson,
		&i.WorkingDirectory,
		&i.Status,
		&i.OutputArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationArtifacts = `-- name: ListConversationArtifacts :many
SELECT id, source_file_id, conversation_id, path, kind, text, sha256, created_at FROM artifacts
WHERE conversation_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListConversationArtifacts(ctx context.Context, conversationID sql.NullInt64) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listConversationArtifacts, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.SourceFileID,
			&i.ConversationID,
			&i.Path,
			&i.Kind,
			&i.Text,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileMentions = `-- name: ListFileMentions :many
SELECT id, file_id, message_id, tool_call_id, mention_kind, line_start, line_end, snippet FROM file_mentions
WHERE file_id = ?
ORDER BY id
`

func (q *Queries) ListFileMentions(ctx context.Context, fileID int64) ([]FileMention, error) {
	rows, err := q.db.QueryContext(ctx, listFileMentions, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileMention{}
	for rows.Next() {
		var i FileMention
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.MessageID,
			&i.ToolCallID,
			&i.MentionKind,
			&i.LineStart,
			&i.LineEnd,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilePatches = `-- name: ListFilePatches :many
SELECT id, tool_call_id, message_id, file_id, patch_kind, raw_patch, added_lines, removed_lines, parsed_ok FROM patches
WHERE file_id = ?
ORDER BY id
`

func (q *Queries) ListFilePatches(ctx context.Context, fileID sql.NullInt64) ([]Patch, error) {
	rows, err := q.db.QueryContext(ctx, listFilePatches, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patch{}
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.ToolCallID,
			&i.MessageID,
			&i.FileID,
			&i.PatchKind,
			&i.RawPatch,
			&i.AddedLines,
			&i.RemovedLines,
			&i.ParsedOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageFileMentions = `-- name: ListMessageFileMentions :many
SELECT id, file_id, message_id, tool_call_id, mention_kind, line_start, line_end, snippet FROM file_mentions
WHERE message_id = ?
ORDER BY id
`

func (q *Queries) ListMessageFileMentions(ctx context.Context, messageID sql.NullInt64) ([]FileMention, error) {
	rows, err := q.db.QueryContext(ctx, listMessageFileMentions, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileMention{}
	for rows.Next() {
		var i FileMention
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.MessageID,
			&i.ToolCallID,
			&i.MentionKind,
			&i.LineStart,
			&i.LineEnd,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagePatches = `-- name: ListMessagePatches :many
SELECT id, tool_call_id, message_id, file_id, patch_kind, raw_patch, added_lines, removed_lines, parsed_ok FROM patches
WHERE message_id = ?
ORDER BY id
`

func (q *Queries) ListMessagePatches(ctx context.Context, messageID sql.NullInt64) ([]Patch, error) {
	rows, err := q.db.QueryContext(ctx, listMessagePatches, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patch{}
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.ToolCallID,
			&i.MessageID,
			&i.FileID,
			&i.PatchKind,
			&i.RawPatch,
			&i.AddedLines,
			&i.RemovedLines,
			&i.ParsedOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageToolCalls = `-- name: ListMessageToolCalls :many
SELECT id, message_id, block_id, tool_name, arguments_json, working_directory, status, output_artifact_id, created_at FROM tool_calls
WHERE message_id = ?
ORDER BY id
`

func (q *Queries) ListMessageToolCalls(ctx context.Context, messageID int64) ([]ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, listMessageToolCalls, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.BlockID,
			&i.ToolName,
			&i.ArgumentsJson,
			&i.WorkingDirectory,
			&i.Status,
			&i.OutputArtifactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedFilesForConversations = `-- name: ListRelatedFilesForConversations :many
SELECT
    f.path,
    coalesce(p.name, p.slug, '') AS project_name,
    count(*) AS mentions
FROM file_mentions fm
JOIN files f ON f.id = fm.file_id
LEFT JOIN projects p ON p.id = f.project_id
JOIN messages m ON m.id = fm.message_id
WHERE m.conversation_id IN (/*SLICE:conversation_ids*/?)
GROUP BY f.id
ORDER BY mentions DESC, f.path
LIMIT ?
`

type ListRelatedFilesForConversationsParams struct {
	ConversationIds []int64 `json:"conversation_ids"`
	Limit           int64   `json:"limit"`
}

type ListRelatedFilesForConversationsRow struct {
	Path        string `json:"path"`
	ProjectName string `json:"project_name"`
	Mentions    int64  `json:"mentions"`
}

func (q *Queries) ListRelatedFilesForConversations(ctx context.Context, arg ListRelatedFilesForConversationsParams) ([]ListRelatedFilesForConversationsRow, error) {
	query := listRelatedFilesForConversations
	var queryParams []interface{}
	if len(arg.ConversationIds) > 0 {
		for _, v := range arg.ConversationIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:conversation_ids*/?", strings.Repeat(",?", len(arg.ConversationIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:conversation_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelatedFilesForConversationsRow{}
	for rows.Next() {
		var i ListRelatedFilesForConversationsRow
		if err := rows.Scan(&i.Path, &i.ProjectName, &i.Mentions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsForConversations = `-- name: ListToolCallsForConversations :many
SELECT
    tc.id,
    tc.tool_name,
    coalesce(tc.status, '') AS status,
    coalesce(tc.created_at, '') AS created_at,
    tc.message_id,
    coalesce(tc.arguments_json, '') AS arguments_json,
    coalesce(tc.working_directory, '') AS working_directory
FROM tool_calls tc
JOIN messages m ON m.id = tc.message_id
WHERE m.conversation_id IN (/*SLICE:conversation_ids*/?)
ORDER BY coalesce(tc.created_at, '') DESC, tc.id DESC
LIMIT ?
`

type ListToolCallsForConversationsParams struct {
	ConversationIds []int64 `json:"conversation_ids"`
	Limit           int64   `json:"limit"`
}

type ListToolCallsForConversationsRow struct {
	ID               int64  `json:"id"`
	ToolName         string `json:"tool_name"`
	Status           string `json:"status"`
	CreatedAt        string `json:"created_at"`
	MessageID        int64  `json:"message_id"`
	ArgumentsJson    string `json:"arguments_json"`
	WorkingDirectory string `json:"working_directory"`
}

func (q *Queries) ListToolCallsForConversations(ctx context.Context, arg ListToolCallsForConversationsParams) ([]ListToolCallsForConversationsRow, error) {
	query := listToolCallsForConversations
	var queryParams []interface{}
	if len(arg.ConversationIds) > 0 {
		for _, v := range arg.ConversationIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:conversation_ids*/?", strings.Repeat(",?", len(arg.ConversationIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:conversation_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolCallsForConversationsRow{}
	for rows.Next() {
		var i ListToolCallsForConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ToolName,
			&i.Status,
			&i.CreatedAt,
			&i.MessageID,
			&i.ArgumentsJson,
			&i.WorkingDirectory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
