// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"
	"database/sql"
)

const searchFileContext = `-- name: SearchFileContext :many
SELECT
    f.path,
    coalesce(f.normalized_path, f.path) AS normalized_path,
    coalesce(p.name, p.slug, '') AS project_name,
    coalesce(p.canonical_path, p.git_root, '') AS project_dir,
    c.id AS conversation_id,
    coalesce(c.title, '') AS conversation_title,
    count(fm.id) AS mentions,
    max(coalesce(m.created_at, c.started_at, '')) AS last_mentioned_at,
    group_concat(DISTINCT fm.mention_kind) AS mention_kinds,
    coalesce((
        SELECT substr(coalesce(fm2.snippet, ''), 1, 400)
        FROM file_mentions fm2
        JOIN messages m2 ON m2.id = fm2.message_id
        WHERE fm2.file_id = f.id
          AND m2.conversation_id = c.id
          AND coalesce(fm2.snippet, '') != ''
        ORDER BY coalesce(m2.created_at, '') DESC, fm2.id DESC
        LIMIT 1
    ), '') AS snippet
FROM files f
JOIN file_mentions fm ON fm.file_id = f.id
JOIN messages m ON m.id = fm.message_id
JOIN conversations c ON c.id = m.conversation_id
LEFT JOIN projects p ON p.id = f.project_id
WHERE (?1 = 0 OR f.project_id = ?2)
  AND (
    (?3 != '' AND f.basename = ?3)
    OR coalesce(f.normalized_path, f.path) LIKE ?4
    OR coalesce(f.normalized_path, f.path) LIKE ?5
  )
GROUP BY f.id, c.id
ORDER BY last_mentioned_at DESC, f.path, c.id
LIMIT ?6
`

type SearchFileContextParams struct {
	EnableProject interface{}    `json:"enable_project"`
	ProjectID     sql.NullInt64  `json:"project_id"`
	Basename      interface{}    `json:"basename"`
	PathContains  sql.NullString `json:"path_contains"`
	PathSuffix    sql.NullString `json:"path_suffix"`
	ResultLimit   int64          `json:"result_limit"`
}

type SearchFileContextRow struct {
	Path              string      `json:"path"`
	NormalizedPath    string      `json:"normalized_path"`
	ProjectName       string      `json:"project_name"`
	ProjectDir        string      `json:"project_dir"`
	ConversationID    int64       `json:"conversation_id"`
	ConversationTitle string      `json:"conversation_title"`
	Mentions          int64       `json:"mentions"`
	LastMentionedAt   interface{} `json:"last_mentioned_at"`
	MentionKinds      string      `json:"mention_kinds"`
	Snippet           interface{} `json:"snippet"`
}

func (q *Queries) SearchFileContext(ctx context.Context, arg SearchFileContextParams) ([]SearchFileContextRow, error) {
	rows, err := q.db.QueryContext(ctx, searchFileContext,
		arg.EnableProject,
		arg.ProjectID,
		arg.Basename,
		arg.PathContains,
		arg.PathSuffix,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFileContextRow{}
	for rows.Next() {
		var i SearchFileContextRow
		if err := rows.Scan(
			&i.Path,
			&i.NormalizedPath,
			&i.ProjectName,
			&i.ProjectDir,
			&i.ConversationID,
			&i.ConversationTitle,
			&i.Mentions,
			&i.LastMentionedAt,
			&i.MentionKinds,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
