// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package db

import (
	"context"
	"database/sql"
)

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (type, value, label, normalized_value, first_seen_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, type, value, label, normalized_value, first_seen_at, last_seen_at
`

type CreateEntityParams struct {
	Type            string         `json:"type"`
	Value           string         `json:"value"`
	Label           sql.NullString `json:"label"`
	NormalizedValue string         `json:"normalized_value"`
	FirstSeenAt     sql.NullString `json:"first_seen_at"`
	LastSeenAt      sql.NullString `json:"last_seen_at"`
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, createEntity,
		arg.Type,
		arg.Value,
		arg.Label,
		arg.NormalizedValue,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.Label,
		&i.NormalizedValue,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const createEntityMention = `-- name: CreateEntityMention :one
INSERT INTO entity_mentions (
    entity_id, message_id, memory_item_id, project_id, context, confidence
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, entity_id, message_id, memory_item_id, project_id, context, confidence
`

type CreateEntityMentionParams struct {
	EntityID     int64          `json:"entity_id"`
	MessageID    sql.NullInt64  `json:"message_id"`
	MemoryItemID sql.NullInt64  `json:"memory_item_id"`
	ProjectID    sql.NullInt64  `json:"project_id"`
	Context      sql.NullString `json:"context"`
	Confidence   float64        `json:"confidence"`
}

func (q *Queries) CreateEntityMention(ctx context.Context, arg CreateEntityMentionParams) (EntityMention, error) {
	row := q.db.QueryRowContext(ctx, createEntityMention,
		arg.EntityID,
		arg.MessageID,
		arg.MemoryItemID,
		arg.ProjectID,
		arg.Context,
		arg.Confidence,
	)
	var i EntityMention
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.MessageID,
		&i.MemoryItemID,
		&i.ProjectID,
		&i.Context,
		&i.Confidence,
	)
	return i, err
}

const createMemoryItem = `-- name: CreateMemoryItem :one
INSERT INTO memory_items (
    project_id, conversation_id, message_id, kind, title, body,
    confidence, importance, happened_at, evidence_json
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, conversation_id, message_id, kind, title, body, confidence, importance, happened_at, created_at, evidence_json
`

type CreateMemoryItemParams struct {
	ProjectID      sql.NullInt64  `json:"project_id"`
	ConversationID sql.NullInt64  `json:"conversation_id"`
	MessageID      sql.NullInt64  `json:"message_id"`
	Kind           string         `json:"kind"`
	Title          sql.NullString `json:"title"`
	Body           string         `json:"body"`
	Confidence     float64        `json:"confidence"`
	Importance     int64          `json:"importance"`
	HappenedAt     sql.NullString `json:"happened_at"`
	EvidenceJson   sql.NullString `json:"evidence_json"`
}

func (q *Queries) CreateMemoryItem(ctx context.Context, arg CreateMemoryItemParams) (MemoryItem, error) {
	row := q.db.QueryRowContext(ctx, createMemoryItem,
		arg.ProjectID,
		arg.ConversationID,
		arg.MessageID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Confidence,
		arg.Importance,
		arg.HappenedAt,
		arg.EvidenceJson,
	)
	var i MemoryItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConversationID,
		&i.MessageID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Confidence,
		&i.Importance,
		&i.HappenedAt,
		&i.CreatedAt,
		&i.EvidenceJson,
	)
	return i, err
}

const createTaskItem = `-- name: CreateTaskItem :one
INSERT INTO task_items (
    project_id, conversation_id, memory_item_id, title, step_number,
    status, body, evidence_message_id, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, conversation_id, memory_item_id, title, step_number, status, body, evidence_message_id, updated_at
`

type CreateTaskItemParams struct {
	ProjectID         sql.NullInt64  `json:"project_id"`
	ConversationID    sql.NullInt64  `json:"conversation_id"`
	MemoryItemID      sql.NullInt64  `json:"memory_item_id"`
	Title             string         `json:"title"`
	StepNumber        sql.NullInt64  `json:"step_number"`
	Status            string         `json:"status"`
	Body              sql.NullString `json:"body"`
	EvidenceMessageID sql.NullInt64  `json:"evidence_message_id"`
	UpdatedAt         sql.NullString `json:"updated_at"`
}

func (q *Queries) CreateTaskItem(ctx context.Context, arg CreateTaskItemParams) (TaskItem, error) {
	row := q.db.QueryRowContext(ctx, createTaskItem,
		arg.ProjectID,
		arg.ConversationID,
		arg.MemoryItemID,
		arg.Title,
		arg.StepNumber,
		arg.Status,
		arg.Body,
		arg.EvidenceMessageID,
		arg.UpdatedAt,
	)
	var i TaskItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConversationID,
		&i.MemoryItemID,
		&i.Title,
		&i.StepNumber,
		&i.Status,
		&i.Body,
		&i.EvidenceMessageID,
		&i.UpdatedAt,
	)
	return i, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (name, normalized_name)
VALUES (?, ?)
RETURNING id, name, normalized_name
`

type CreateTopicParams struct {
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, createTopic, arg.Name, arg.NormalizedName)
	var i Topic
	err := row.Scan(&i.ID, &i.Name, &i.NormalizedName)
	return i, err
}

const deleteEntity = `-- name: DeleteEntity :exec
DELETE FROM entities
WHERE id = ?
`

func (q *Queries) DeleteEntity(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntity, id)
	return err
}

const deleteEntityMention = `-- name: DeleteEntityMention :exec
DELETE FROM entity_mentions
WHERE id = ?
`

func (q *Queries) DeleteEntityMention(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntityMention, id)
	return err
}

const deleteMemoryItem = `-- name: DeleteMemoryItem :exec
DELETE FROM memory_items
WHERE id = ?
`

func (q *Queries) DeleteMemoryItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMemoryItem, id)
	return err
}

const deleteTaskItem = `-- name: DeleteTaskItem :exec
DELETE FROM task_items
WHERE id = ?
`

func (q *Queries) DeleteTaskItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskItem, id)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics
WHERE id = ?
`

func (q *Queries) DeleteTopic(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTopic, id)
	return err
}

const getEntity = `-- name: GetEntity :one
SELECT id, type, value, label, normalized_value, first_seen_at, last_seen_at FROM entities
WHERE id = ?
`

func (q *Queries) GetEntity(ctx context.Context, id int64) (Entity, error) {
	row := q.db.QueryRowContext(ctx, getEntity, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.Label,
		&i.NormalizedValue,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getMemoryItem = `-- name: GetMemoryItem :one
SELECT id, project_id, conversation_id, message_id, kind, title, body, confidence, importance, happened_at, created_at, evidence_json FROM memory_items
WHERE id = ?
`

func (q *Queries) GetMemoryItem(ctx context.Context, id int64) (MemoryItem, error) {
	row := q.db.QueryRowContext(ctx, getMemoryItem, id)
	var i MemoryItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConversationID,
		&i.MessageID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Confidence,
		&i.Importance,
		&i.HappenedAt,
		&i.CreatedAt,
		&i.EvidenceJson,
	)
	return i, err
}

const getTaskItem = `-- name: GetTaskItem :one
SELECT id, project_id, conversation_id, memory_item_id, title, step_number, status, body, evidence_message_id, updated_at FROM task_items
WHERE id = ?
`

func (q *Queries) GetTaskItem(ctx context.Context, id int64) (TaskItem, error) {
	row := q.db.QueryRowContext(ctx, getTaskItem, id)
	var i TaskItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConversationID,
		&i.MemoryItemID,
		&i.Title,
		&i.StepNumber,
		&i.Status,
		&i.Body,
		&i.EvidenceMessageID,
		&i.UpdatedAt,
	)
	return i, err
}

const linkConversationTopic = `-- name: LinkConversationTopic :exec
INSERT INTO conversation_topics (conversation_id, topic_id, score)
VALUES (?, ?, ?)
ON CONFLICT(conversation_id, topic_id) DO UPDATE SET
    score = excluded.score
`

type LinkConversationTopicParams struct {
	ConversationID int64   `json:"conversation_id"`
	TopicID        int64   `json:"topic_id"`
	Score          float64 `json:"score"`
}

func (q *Queries) LinkConversationTopic(ctx context.Context, arg LinkConversationTopicParams) error {
	_, err := q.db.ExecContext(ctx, linkConversationTopic, arg.ConversationID, arg.TopicID, arg.Score)
	return err
}

const listConversationTopics = `-- name: ListConversationTopics :many
SELECT t.id, t.name, t.normalized_name, ct.score
FROM conversation_topics ct
JOIN topics t ON t.id = ct.topic_id
WHERE ct.conversation_id = ?
ORDER BY ct.score DESC, t.normalized_name
`

type ListConversationTopicsRow struct {
	ID             int64   `json:"id"`
	Name           string  `json:"name"`
	NormalizedName string  `json:"normalized_name"`
	Score          float64 `json:"score"`
}

func (q *Queries) ListConversationTopics(ctx context.Context, conversationID int64) ([]ListConversationTopicsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationTopics, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationTopicsRow{}
	for rows.Next() {
		var i ListConversationTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByType = `-- name: ListEntitiesByType :many
SELECT id, type, value, label, normalized_value, first_seen_at, last_seen_at FROM entities
WHERE type = ?
ORDER BY last_seen_at DESC, value
`

func (q *Queries) ListEntitiesByType(ctx context.Context, type_ string) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, listEntitiesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Value,
			&i.Label,
			&i.NormalizedValue,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityMentions = `-- name: ListEntityMentions :many
SELECT id, entity_id, message_id, memory_item_id, project_id, context, confidence FROM entity_mentions
WHERE entity_id = ?
ORDER BY id
`

func (q *Queries) ListEntityMentions(ctx context.Context, entityID int64) ([]EntityMention, error) {
	rows, err := q.db.QueryContext(ctx, listEntityMentions, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityMention{}
	for rows.Next() {
		var i EntityMention
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.MessageID,
			&i.MemoryItemID,
			&i.ProjectID,
			&i.Context,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryItems = `-- name: ListMemoryItems :many
SELECT id, project_id, conversation_id, message_id, kind, title, body, confidence, importance, happened_at, created_at, evidence_json FROM memory_items
ORDER BY coalesce(happened_at, created_at) DESC, id DESC
LIMIT ? OFFSET ?
`

type ListMemoryItemsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListMemoryItems(ctx context.Context, arg ListMemoryItemsParams) ([]MemoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryItem{}
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConversationID,
			&i.MessageID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Confidence,
			&i.Importance,
			&i.HappenedAt,
			&i.CreatedAt,
			&i.EvidenceJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryItemsByKind = `-- name: ListMemoryItemsByKind :many
SELECT id, project_id, conversation_id, message_id, kind, title, body, confidence, importance, happened_at, created_at, evidence_json FROM memory_items
WHERE kind = ?
ORDER BY coalesce(happened_at, created_at) DESC, id DESC
LIMIT ? OFFSET ?
`

type ListMemoryItemsByKindParams struct {
	Kind   string `json:"kind"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListMemoryItemsByKind(ctx context.Context, arg ListMemoryItemsByKindParams) ([]MemoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryItemsByKind, arg.Kind, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryItem{}
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConversationID,
			&i.MessageID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Confidence,
			&i.Importance,
			&i.HappenedAt,
			&i.CreatedAt,
			&i.EvidenceJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMemoryItems = `-- name: ListProjectMemoryItems :many
SELECT id, project_id, conversation_id, message_id, kind, title, body, confidence, importance, happened_at, created_at, evidence_json FROM memory_items
WHERE project_id = ?
ORDER BY coalesce(happened_at, created_at) DESC, id DESC
LIMIT ? OFFSET ?
`

type ListProjectMemoryItemsParams struct {
	ProjectID sql.NullInt64 `json:"project_id"`
	Limit     int64         `json:"limit"`
	Offset    int64         `json:"offset"`
}

func (q *Queries) ListProjectMemoryItems(ctx context.Context, arg ListProjectMemoryItemsParams) ([]MemoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMemoryItems, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryItem{}
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConversationID,
			&i.MessageID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Confidence,
			&i.Importance,
			&i.HappenedAt,
			&i.CreatedAt,
			&i.EvidenceJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT id, project_id, conversation_id, memory_item_id, title, step_number, status, body, evidence_message_id, updated_at FROM task_items
WHERE project_id = ?
ORDER BY step_number, id
`

func (q *Queries) ListProjectTasks(ctx context.Context, projectID sql.NullInt64) ([]TaskItem, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskItem{}
	for rows.Next() {
		var i TaskItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConversationID,
			&i.MemoryItemID,
			&i.Title,
			&i.StepNumber,
			&i.Status,
			&i.Body,
			&i.EvidenceMessageID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasksByStatus = `-- name: ListProjectTasksByStatus :many
SELECT id, project_id, conversation_id, memory_item_id, title, step_number, status, body, evidence_message_id, updated_at FROM task_items
WHERE project_id = ? AND status = ?
ORDER BY step_number, id
`

type ListProjectTasksByStatusParams struct {
	ProjectID sql.NullInt64 `json:"project_id"`
	Status    string        `json:"status"`
}

func (q *Queries) ListProjectTasksByStatus(ctx context.Context, arg ListProjectTasksByStatusParams) ([]TaskItem, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTasksByStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskItem{}
	for rows.Next() {
		var i TaskItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConversationID,
			&i.MemoryItemID,
			&i.Title,
			&i.StepNumber,
			&i.Status,
			&i.Body,
			&i.EvidenceMessageID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
SELECT id, name, normalized_name FROM topics
ORDER BY normalized_name
`

func (q *Queries) ListTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(&i.ID, &i.Name, &i.NormalizedName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkConversationTopic = `-- name: UnlinkConversationTopic :exec
DELETE FROM conversation_topics
WHERE conversation_id = ? AND topic_id = ?
`

type UnlinkConversationTopicParams struct {
	ConversationID int64 `json:"conversation_id"`
	TopicID        int64 `json:"topic_id"`
}

func (q *Queries) UnlinkConversationTopic(ctx context.Context, arg UnlinkConversationTopicParams) error {
	_, err := q.db.ExecContext(ctx, unlinkConversationTopic, arg.ConversationID, arg.TopicID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE task_items
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, project_id, conversation_id, memory_item_id, title, step_number, status, body, evidence_message_id, updated_at
`

type UpdateTaskStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (TaskItem, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	var i TaskItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConversationID,
		&i.MemoryItemID,
		&i.Title,
		&i.StepNumber,
		&i.Status,
		&i.Body,
		&i.EvidenceMessageID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEntity = `-- name: UpsertEntity :one
INSERT INTO entities (type, value, label, normalized_value, first_seen_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(type, normalized_value) DO UPDATE SET
    value = excluded.value,
    label = excluded.label,
    last_seen_at = excluded.last_seen_at
RETURNING id, type, value, label, normalized_value, first_seen_at, last_seen_at
`

type UpsertEntityParams struct {
	Type            string         `json:"type"`
	Value           string         `json:"value"`
	Label           sql.NullString `json:"label"`
	NormalizedValue string         `json:"normalized_value"`
	FirstSeenAt     sql.NullString `json:"first_seen_at"`
	LastSeenAt      sql.NullString `json:"last_seen_at"`
}

func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, upsertEntity,
		arg.Type,
		arg.Value,
		arg.Label,
		arg.NormalizedValue,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.Label,
		&i.NormalizedValue,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertTopic = `-- name: UpsertTopic :one
INSERT INTO topics (name, normalized_name)
VALUES (?, ?)
ON CONFLICT(normalized_name) DO UPDATE SET
    name = excluded.name
RETURNING id, name, normalized_name
`

type UpsertTopicParams struct {
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, upsertTopic, arg.Name, arg.NormalizedName)
	var i Topic
	err := row.Scan(&i.ID, &i.Name, &i.NormalizedName)
	return i, err
}
