// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (project_id, path, normalized_path, kind)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, path, normalized_path, kind
`

type CreateFileParams struct {
	ProjectID      sql.NullInt64  `json:"project_id"`
	Path           string         `json:"path"`
	NormalizedPath sql.NullString `json:"normalized_path"`
	Kind           sql.NullString `json:"kind"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ProjectID,
		arg.Path,
		arg.NormalizedPath,
		arg.Kind,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.NormalizedPath,
		&i.Kind,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    canonical_path, slug, name, git_root, remote_url, first_seen_at, last_seen_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, canonical_path, slug, name, git_root, remote_url, first_seen_at, last_seen_at
`

type CreateProjectParams struct {
	CanonicalPath sql.NullString `json:"canonical_path"`
	Slug          string         `json:"slug"`
	Name          sql.NullString `json:"name"`
	GitRoot       sql.NullString `json:"git_root"`
	RemoteUrl     sql.NullString `json:"remote_url"`
	FirstSeenAt   sql.NullString `json:"first_seen_at"`
	LastSeenAt    sql.NullString `json:"last_seen_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.CanonicalPath,
		arg.Slug,
		arg.Name,
		arg.GitRoot,
		arg.RemoteUrl,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CanonicalPath,
		&i.Slug,
		&i.Name,
		&i.GitRoot,
		&i.RemoteUrl,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, project_id, path, normalized_path, kind FROM files
WHERE id = ?
`

func (q *Queries) GetFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.NormalizedPath,
		&i.Kind,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, canonical_path, slug, name, git_root, remote_url, first_seen_at, last_seen_at FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CanonicalPath,
		&i.Slug,
		&i.Name,
		&i.GitRoot,
		&i.RemoteUrl,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, canonical_path, slug, name, git_root, remote_url, first_seen_at, last_seen_at FROM projects
WHERE slug = ?
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CanonicalPath,
		&i.Slug,
		&i.Name,
		&i.GitRoot,
		&i.RemoteUrl,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listProjectFiles = `-- name: ListProjectFiles :many
SELECT id, project_id, path, normalized_path, kind FROM files
WHERE project_id = ?
ORDER BY path
`

func (q *Queries) ListProjectFiles(ctx context.Context, projectID sql.NullInt64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listProjectFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Path,
			&i.NormalizedPath,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, canonical_path, slug, name, git_root, remote_url, first_seen_at, last_seen_at FROM projects
ORDER BY coalesce(last_seen_at, first_seen_at) DESC, slug
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalPath,
			&i.Slug,
			&i.Name,
			&i.GitRoot,
			&i.RemoteUrl,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET canonical_path = ?,
    slug = ?,
    name = ?,
    git_root = ?,
    remote_url = ?,
    first_seen_at = ?,
    last_seen_at = ?
WHERE id = ?
RETURNING id, canonical_path, slug, name, git_root, remote_url, first_seen_at, last_seen_at
`

type UpdateProjectParams struct {
	CanonicalPath sql.NullString `json:"canonical_path"`
	Slug          string         `json:"slug"`
	Name          sql.NullString `json:"name"`
	GitRoot       sql.NullString `json:"git_root"`
	RemoteUrl     sql.NullString `json:"remote_url"`
	FirstSeenAt   sql.NullString `json:"first_seen_at"`
	LastSeenAt    sql.NullString `json:"last_seen_at"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.CanonicalPath,
		arg.Slug,
		arg.Name,
		arg.GitRoot,
		arg.RemoteUrl,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CanonicalPath,
		&i.Slug,
		&i.Name,
		&i.GitRoot,
		&i.RemoteUrl,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertFile = `-- name: UpsertFile :one
INSERT INTO files (project_id, path, normalized_path, kind)
VALUES (?, ?, ?, ?)
ON CONFLICT(project_id, path) DO UPDATE SET
    normalized_path = excluded.normalized_path,
    kind = excluded.kind
RETURNING id, project_id, path, normalized_path, kind
`

type UpsertFileParams struct {
	ProjectID      sql.NullInt64  `json:"project_id"`
	Path           string         `json:"path"`
	NormalizedPath sql.NullString `json:"normalized_path"`
	Kind           sql.NullString `json:"kind"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, upsertFile,
		arg.ProjectID,
		arg.Path,
		arg.NormalizedPath,
		arg.Kind,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.NormalizedPath,
		&i.Kind,
	)
	return i, err
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (
    canonical_path, slug, name, git_root, remote_url, first_seen_at, last_seen_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(slug) DO UPDATE SET
    canonical_path = excluded.canonical_path,
    name = excluded.name,
    git_root = excluded.git_root,
    remote_url = excluded.remote_url,
    last_seen_at = excluded.last_seen_at
RETURNING id, canonical_path, slug, name, git_root, remote_url, first_seen_at, last_seen_at
`

type UpsertProjectParams struct {
	CanonicalPath sql.NullString `json:"canonical_path"`
	Slug          string         `json:"slug"`
	Name          sql.NullString `json:"name"`
	GitRoot       sql.NullString `json:"git_root"`
	RemoteUrl     sql.NullString `json:"remote_url"`
	FirstSeenAt   sql.NullString `json:"first_seen_at"`
	LastSeenAt    sql.NullString `json:"last_seen_at"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, upsertProject,
		arg.CanonicalPath,
		arg.Slug,
		arg.Name,
		arg.GitRoot,
		arg.RemoteUrl,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CanonicalPath,
		&i.Slug,
		&i.Name,
		&i.GitRoot,
		&i.RemoteUrl,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
