// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFileMention(ctx context.Context, arg CreateFileMentionParams) (FileMention, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageBlock(ctx context.Context, arg CreateMessageBlockParams) (MessageBlock, error)
	CreateParseError(ctx context.Context, arg CreateParseErrorParams) (ParseError, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	CreateSourceFile(ctx context.Context, arg CreateSourceFileParams) (SourceFile, error)
	CreateToolCall(ctx context.Context, arg CreateToolCallParams) (ToolCall, error)
	DeleteConversation(ctx context.Context, id int64) error
	DeleteFile(ctx context.Context, id int64) error
	DeleteFileMention(ctx context.Context, id int64) error
	DeleteFileMentionsForMessage(ctx context.Context, messageID sql.NullInt64) error
	DeleteMessage(ctx context.Context, id int64) error
	DeleteMessageBlock(ctx context.Context, id int64) error
	DeleteParseError(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteSource(ctx context.Context, id int64) error
	DeleteSourceFile(ctx context.Context, id int64) error
	DeleteToolCall(ctx context.Context, id int64) error
	DeleteToolCallFileMentionsForMessage(ctx context.Context, messageID int64) error
	DeleteToolCallsForMessage(ctx context.Context, messageID int64) error
	GetConversation(ctx context.Context, id int64) (Conversation, error)
	GetConversationByExternalID(ctx context.Context, arg GetConversationByExternalIDParams) (Conversation, error)
	GetFile(ctx context.Context, id int64) (File, error)
	GetIndexStats(ctx context.Context) (GetIndexStatsRow, error)
	GetMessage(ctx context.Context, id int64) (Message, error)
	GetMessageByRawLine(ctx context.Context, arg GetMessageByRawLineParams) (Message, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetSource(ctx context.Context, id int64) (Source, error)
	GetSourceByKindRoot(ctx context.Context, arg GetSourceByKindRootParams) (Source, error)
	GetSourceFile(ctx context.Context, id int64) (SourceFile, error)
	GetSourceFileByPath(ctx context.Context, arg GetSourceFileByPathParams) (SourceFile, error)
	GetToolCall(ctx context.Context, id int64) (ToolCall, error)
	ListConversationMessages(ctx context.Context, conversationID int64) ([]Message, error)
	ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error)
	ListFileMentions(ctx context.Context, fileID int64) ([]FileMention, error)
	ListIndexStatsBySource(ctx context.Context) ([]ListIndexStatsBySourceRow, error)
	ListMessageBlocks(ctx context.Context, messageID int64) ([]MessageBlock, error)
	ListMessageFileMentions(ctx context.Context, messageID sql.NullInt64) ([]FileMention, error)
	ListMessageToolCalls(ctx context.Context, messageID int64) ([]ToolCall, error)
	ListParseErrorsForSourceFile(ctx context.Context, sourceFileID sql.NullInt64) ([]ParseError, error)
	ListProjectConversations(ctx context.Context, arg ListProjectConversationsParams) ([]Conversation, error)
	ListProjectFiles(ctx context.Context, projectID sql.NullInt64) ([]File, error)
	ListProjectSummaries(ctx context.Context) ([]ListProjectSummariesRow, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListRelatedFilesForConversations(ctx context.Context, arg ListRelatedFilesForConversationsParams) ([]ListRelatedFilesForConversationsRow, error)
	ListSourceFiles(ctx context.Context, sourceID int64) ([]SourceFile, error)
	ListSources(ctx context.Context) ([]Source, error)
	ListToolCallsForConversations(ctx context.Context, arg ListToolCallsForConversationsParams) ([]ListToolCallsForConversationsRow, error)
	SearchFileContext(ctx context.Context, arg SearchFileContextParams) ([]SearchFileContextRow, error)
	SearchMessageHits(ctx context.Context, arg SearchMessageHitsParams) ([]SearchMessageHitsRow, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
	UpsertConversation(ctx context.Context, arg UpsertConversationParams) (Conversation, error)
	UpsertFile(ctx context.Context, arg UpsertFileParams) (File, error)
	UpsertMessage(ctx context.Context, arg UpsertMessageParams) (Message, error)
	UpsertMessageBlock(ctx context.Context, arg UpsertMessageBlockParams) (MessageBlock, error)
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error)
	UpsertSource(ctx context.Context, arg UpsertSourceParams) (Source, error)
	UpsertSourceFile(ctx context.Context, arg UpsertSourceFileParams) (SourceFile, error)
}

var _ Querier = (*Queries)(nil)
