// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"database/sql"
)

const searchArtifactHits = `-- name: SearchArtifactHits :many
SELECT
    'artifact' AS result_type,
    bm25(artifact_fts) AS score,
    coalesce(p.name, p.slug, '') AS project_name,
    coalesce(p.canonical_path, p.git_root, '') AS project_dir,
    coalesce(a.conversation_id, 0) AS conversation_id,
    '' AS conversation_title,
    a.id AS entity_id,
    a.kind AS role,
    coalesce(a.created_at, '') AS created_at,
    coalesce(substr(a.path || ' ' || coalesce(a.text, ''), 1, 400), '') AS snippet
FROM artifact_fts(?1) f
JOIN artifacts a ON a.id = f.rowid
LEFT JOIN conversations c ON c.id = a.conversation_id
LEFT JOIN projects p ON p.id = c.project_id
WHERE (?2 = 0 OR c.project_id = ?3)
  AND (?4 = 0 OR coalesce(a.created_at, '') >= ?5)
ORDER BY score
LIMIT ?6
`

type SearchArtifactHitsParams struct {
	FtsQuery      interface{}    `json:"fts_query"`
	EnableProject interface{}    `json:"enable_project"`
	ProjectID     sql.NullInt64  `json:"project_id"`
	EnableSince   interface{}    `json:"enable_since"`
	Since         sql.NullString `json:"since"`
	ResultLimit   int64          `json:"result_limit"`
}

type SearchArtifactHitsRow struct {
	ResultType        string      `json:"result_type"`
	Score             float64     `json:"score"`
	ProjectName       string      `json:"project_name"`
	ProjectDir        string      `json:"project_dir"`
	ConversationID    int64       `json:"conversation_id"`
	ConversationTitle string      `json:"conversation_title"`
	EntityID          int64       `json:"entity_id"`
	Role              string      `json:"role"`
	CreatedAt         string      `json:"created_at"`
	Snippet           interface{} `json:"snippet"`
}

func (q *Queries) SearchArtifactHits(ctx context.Context, arg SearchArtifactHitsParams) ([]SearchArtifactHitsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArtifactHits,
		arg.FtsQuery,
		arg.EnableProject,
		arg.ProjectID,
		arg.EnableSince,
		arg.Since,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArtifactHitsRow{}
	for rows.Next() {
		var i SearchArtifactHitsRow
		if err := rows.Scan(
			&i.ResultType,
			&i.Score,
			&i.ProjectName,
			&i.ProjectDir,
			&i.ConversationID,
			&i.ConversationTitle,
			&i.EntityID,
			&i.Role,
			&i.CreatedAt,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemoryHits = `-- name: SearchMemoryHits :many
SELECT
    'memory' AS result_type,
    bm25(memory_fts) AS score,
    coalesce(p.name, p.slug, '') AS project_name,
    coalesce(p.canonical_path, p.git_root, '') AS project_dir,
    coalesce(mi.conversation_id, 0) AS conversation_id,
    '' AS conversation_title,
    mi.id AS entity_id,
    mi.kind AS role,
    coalesce(mi.happened_at, mi.created_at, '') AS created_at,
    coalesce(substr(mi.title || ' ' || mi.body, 1, 400), '') AS snippet
FROM memory_fts(?1) f
JOIN memory_items mi ON mi.id = f.rowid
LEFT JOIN projects p ON p.id = mi.project_id
WHERE (?2 = 0 OR mi.project_id = ?3)
  AND (?4 = 0 OR coalesce(mi.happened_at, mi.created_at, '') >= ?5)
ORDER BY score
LIMIT ?6
`

type SearchMemoryHitsParams struct {
	FtsQuery      interface{}    `json:"fts_query"`
	EnableProject interface{}    `json:"enable_project"`
	ProjectID     sql.NullInt64  `json:"project_id"`
	EnableSince   interface{}    `json:"enable_since"`
	Since         sql.NullString `json:"since"`
	ResultLimit   int64          `json:"result_limit"`
}

type SearchMemoryHitsRow struct {
	ResultType        string      `json:"result_type"`
	Score             float64     `json:"score"`
	ProjectName       string      `json:"project_name"`
	ProjectDir        string      `json:"project_dir"`
	ConversationID    int64       `json:"conversation_id"`
	ConversationTitle string      `json:"conversation_title"`
	EntityID          int64       `json:"entity_id"`
	Role              string      `json:"role"`
	CreatedAt         string      `json:"created_at"`
	Snippet           interface{} `json:"snippet"`
}

func (q *Queries) SearchMemoryHits(ctx context.Context, arg SearchMemoryHitsParams) ([]SearchMemoryHitsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMemoryHits,
		arg.FtsQuery,
		arg.EnableProject,
		arg.ProjectID,
		arg.EnableSince,
		arg.Since,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMemoryHitsRow{}
	for rows.Next() {
		var i SearchMemoryHitsRow
		if err := rows.Scan(
			&i.ResultType,
			&i.Score,
			&i.ProjectName,
			&i.ProjectDir,
			&i.ConversationID,
			&i.ConversationTitle,
			&i.EntityID,
			&i.Role,
			&i.CreatedAt,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessageHits = `-- name: SearchMessageHits :many
SELECT
    'message' AS result_type,
    bm25(message_fts) AS score,
    coalesce(p.name, p.slug, '') AS project_name,
    coalesce(p.canonical_path, p.git_root, '') AS project_dir,
    c.id AS conversation_id,
    coalesce(c.title, '') AS conversation_title,
    m.id AS entity_id,
    m.role AS role,
    coalesce(m.created_at, c.started_at, strftime('%Y-%m-%dT%H:%M:%SZ', sf.mtime_unix, 'unixepoch'), sf.indexed_at, '') AS created_at,
    coalesce(substr(m.text, 1, 400), '') AS snippet
FROM message_fts(?1) f
JOIN messages m ON m.id = f.rowid
JOIN conversations c ON c.id = m.conversation_id
LEFT JOIN projects p ON p.id = c.project_id
LEFT JOIN source_files sf ON sf.id = m.source_file_id
WHERE (?2 = 0 OR c.project_id = ?3)
  AND (?4 = 0 OR coalesce(m.created_at, c.started_at, strftime('%Y-%m-%dT%H:%M:%SZ', sf.mtime_unix, 'unixepoch'), sf.indexed_at, '') >= ?5)
ORDER BY score
LIMIT ?6
`

type SearchMessageHitsParams struct {
	FtsQuery      interface{}    `json:"fts_query"`
	EnableProject interface{}    `json:"enable_project"`
	ProjectID     sql.NullInt64  `json:"project_id"`
	EnableSince   interface{}    `json:"enable_since"`
	Since         sql.NullString `json:"since"`
	ResultLimit   int64          `json:"result_limit"`
}

type SearchMessageHitsRow struct {
	ResultType        string      `json:"result_type"`
	Score             float64     `json:"score"`
	ProjectName       string      `json:"project_name"`
	ProjectDir        string      `json:"project_dir"`
	ConversationID    int64       `json:"conversation_id"`
	ConversationTitle string      `json:"conversation_title"`
	EntityID          int64       `json:"entity_id"`
	Role              string      `json:"role"`
	CreatedAt         string      `json:"created_at"`
	Snippet           interface{} `json:"snippet"`
}

func (q *Queries) SearchMessageHits(ctx context.Context, arg SearchMessageHitsParams) ([]SearchMessageHitsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMessageHits,
		arg.FtsQuery,
		arg.EnableProject,
		arg.ProjectID,
		arg.EnableSince,
		arg.Since,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessageHitsRow{}
	for rows.Next() {
		var i SearchMessageHitsRow
		if err := rows.Scan(
			&i.ResultType,
			&i.Score,
			&i.ProjectName,
			&i.ProjectDir,
			&i.ConversationID,
			&i.ConversationTitle,
			&i.EntityID,
			&i.Role,
			&i.CreatedAt,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
