// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
)

const searchArtifacts = `-- name: SearchArtifacts :many
SELECT a.id, a.source_file_id, a.conversation_id, a.path, a.kind, a.text, a.sha256, a.created_at
FROM artifact_fts(?) f
JOIN artifacts a ON a.id = f.rowid
ORDER BY rank
LIMIT ?
`

type SearchArtifactsParams struct {
	ArtifactFts interface{} `json:"artifact_fts"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) SearchArtifacts(ctx context.Context, arg SearchArtifactsParams) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, searchArtifacts, arg.ArtifactFts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.SourceFileID,
			&i.ConversationID,
			&i.Path,
			&i.Kind,
			&i.Text,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemoryItems = `-- name: SearchMemoryItems :many
SELECT mi.id, mi.project_id, mi.conversation_id, mi.message_id, mi.kind, mi.title, mi.body, mi.confidence, mi.importance, mi.happened_at, mi.created_at, mi.evidence_json
FROM memory_fts(?) f
JOIN memory_items mi ON mi.id = f.rowid
ORDER BY rank
LIMIT ?
`

type SearchMemoryItemsParams struct {
	MemoryFts interface{} `json:"memory_fts"`
	Limit     int64       `json:"limit"`
}

func (q *Queries) SearchMemoryItems(ctx context.Context, arg SearchMemoryItemsParams) ([]MemoryItem, error) {
	rows, err := q.db.QueryContext(ctx, searchMemoryItems, arg.MemoryFts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryItem{}
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConversationID,
			&i.MessageID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Confidence,
			&i.Importance,
			&i.HappenedAt,
			&i.CreatedAt,
			&i.EvidenceJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
SELECT m.id, m.conversation_id, m.source_file_id, m.role, m.seq, m.created_at, m.text, m.raw_json, m.raw_line, m.content_hash
FROM message_fts(?) f
JOIN messages m ON m.id = f.rowid
ORDER BY rank
LIMIT ?
`

type SearchMessagesParams struct {
	MessageFts interface{} `json:"message_fts"`
	Limit      int64       `json:"limit"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, searchMessages, arg.MessageFts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SourceFileID,
			&i.Role,
			&i.Seq,
			&i.CreatedAt,
			&i.Text,
			&i.RawJson,
			&i.RawLine,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
