// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
	"database/sql"
)

const createParseError = `-- name: CreateParseError :one
INSERT INTO parse_errors (source_file_id, raw_line, parser_version, error, raw_hash)
VALUES (?, ?, ?, ?, ?)
RETURNING id, source_file_id, raw_line, parser_version, error, raw_hash, created_at
`

type CreateParseErrorParams struct {
	SourceFileID  sql.NullInt64  `json:"source_file_id"`
	RawLine       sql.NullInt64  `json:"raw_line"`
	ParserVersion string         `json:"parser_version"`
	Error         string         `json:"error"`
	RawHash       sql.NullString `json:"raw_hash"`
}

func (q *Queries) CreateParseError(ctx context.Context, arg CreateParseErrorParams) (ParseError, error) {
	row := q.db.QueryRowContext(ctx, createParseError,
		arg.SourceFileID,
		arg.RawLine,
		arg.ParserVersion,
		arg.Error,
		arg.RawHash,
	)
	var i ParseError
	err := row.Scan(
		&i.ID,
		&i.SourceFileID,
		&i.RawLine,
		&i.ParserVersion,
		&i.Error,
		&i.RawHash,
		&i.CreatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (kind, root_path, display_name)
VALUES (?, ?, ?)
RETURNING id, kind, root_path, display_name, created_at, updated_at
`

type CreateSourceParams struct {
	Kind        string         `json:"kind"`
	RootPath    string         `json:"root_path"`
	DisplayName sql.NullString `json:"display_name"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource, arg.Kind, arg.RootPath, arg.DisplayName)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RootPath,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSourceFile = `-- name: CreateSourceFile :one
INSERT INTO source_files (
    source_id, project_id, path, kind, size_bytes, mtime_unix, sha256, indexed_at, parser_version
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, source_id, project_id, path, kind, size_bytes, mtime_unix, sha256, indexed_at, parser_version
`

type CreateSourceFileParams struct {
	SourceID      int64          `json:"source_id"`
	ProjectID     sql.NullInt64  `json:"project_id"`
	Path          string         `json:"path"`
	Kind          string         `json:"kind"`
	SizeBytes     sql.NullInt64  `json:"size_bytes"`
	MtimeUnix     sql.NullInt64  `json:"mtime_unix"`
	Sha256        sql.NullString `json:"sha256"`
	IndexedAt     sql.NullString `json:"indexed_at"`
	ParserVersion string         `json:"parser_version"`
}

func (q *Queries) CreateSourceFile(ctx context.Context, arg CreateSourceFileParams) (SourceFile, error) {
	row := q.db.QueryRowContext(ctx, createSourceFile,
		arg.SourceID,
		arg.ProjectID,
		arg.Path,
		arg.Kind,
		arg.SizeBytes,
		arg.MtimeUnix,
		arg.Sha256,
		arg.IndexedAt,
		arg.ParserVersion,
	)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.Sha256,
		&i.IndexedAt,
		&i.ParserVersion,
	)
	return i, err
}

const deleteParseError = `-- name: DeleteParseError :exec
DELETE FROM parse_errors
WHERE id = ?
`

func (q *Queries) DeleteParseError(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteParseError, id)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources
WHERE id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const deleteSourceFile = `-- name: DeleteSourceFile :exec
DELETE FROM source_files
WHERE id = ?
`

func (q *Queries) DeleteSourceFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSourceFile, id)
	return err
}

const getSource = `-- name: GetSource :one
SELECT id, kind, root_path, display_name, created_at, updated_at FROM sources
WHERE id = ?
`

func (q *Queries) GetSource(ctx context.Context, id int64) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RootPath,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByKindRoot = `-- name: GetSourceByKindRoot :one
SELECT id, kind, root_path, display_name, created_at, updated_at FROM sources
WHERE kind = ? AND root_path = ?
`

type GetSourceByKindRootParams struct {
	Kind     string `json:"kind"`
	RootPath string `json:"root_path"`
}

func (q *Queries) GetSourceByKindRoot(ctx context.Context, arg GetSourceByKindRootParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSourceByKindRoot, arg.Kind, arg.RootPath)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RootPath,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceFile = `-- name: GetSourceFile :one
SELECT id, source_id, project_id, path, kind, size_bytes, mtime_unix, sha256, indexed_at, parser_version FROM source_files
WHERE id = ?
`

func (q *Queries) GetSourceFile(ctx context.Context, id int64) (SourceFile, error) {
	row := q.db.QueryRowContext(ctx, getSourceFile, id)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.Sha256,
		&i.IndexedAt,
		&i.ParserVersion,
	)
	return i, err
}

const getSourceFileByPath = `-- name: GetSourceFileByPath :one
SELECT id, source_id, project_id, path, kind, size_bytes, mtime_unix, sha256, indexed_at, parser_version FROM source_files
WHERE source_id = ? AND path = ?
`

type GetSourceFileByPathParams struct {
	SourceID int64  `json:"source_id"`
	Path     string `json:"path"`
}

func (q *Queries) GetSourceFileByPath(ctx context.Context, arg GetSourceFileByPathParams) (SourceFile, error) {
	row := q.db.QueryRowContext(ctx, getSourceFileByPath, arg.SourceID, arg.Path)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.Sha256,
		&i.IndexedAt,
		&i.ParserVersion,
	)
	return i, err
}

const listParseErrorsForSourceFile = `-- name: ListParseErrorsForSourceFile :many
SELECT id, source_file_id, raw_line, parser_version, error, raw_hash, created_at FROM parse_errors
WHERE source_file_id = ?
ORDER BY raw_line, id
`

func (q *Queries) ListParseErrorsForSourceFile(ctx context.Context, sourceFileID sql.NullInt64) ([]ParseError, error) {
	rows, err := q.db.QueryContext(ctx, listParseErrorsForSourceFile, sourceFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParseError{}
	for rows.Next() {
		var i ParseError
		if err := rows.Scan(
			&i.ID,
			&i.SourceFileID,
			&i.RawLine,
			&i.ParserVersion,
			&i.Error,
			&i.RawHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceFiles = `-- name: ListSourceFiles :many
SELECT id, source_id, project_id, path, kind, size_bytes, mtime_unix, sha256, indexed_at, parser_version FROM source_files
WHERE source_id = ?
ORDER BY path
`

func (q *Queries) ListSourceFiles(ctx context.Context, sourceID int64) ([]SourceFile, error) {
	rows, err := q.db.QueryContext(ctx, listSourceFiles, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceFile{}
	for rows.Next() {
		var i SourceFile
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ProjectID,
			&i.Path,
			&i.Kind,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.Sha256,
			&i.IndexedAt,
			&i.ParserVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, kind, root_path, display_name, created_at, updated_at FROM sources
ORDER BY kind, root_path
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.RootPath,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET kind = ?, root_path = ?, display_name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, kind, root_path, display_name, created_at, updated_at
`

type UpdateSourceParams struct {
	Kind        string         `json:"kind"`
	RootPath    string         `json:"root_path"`
	DisplayName sql.NullString `json:"display_name"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, updateSource,
		arg.Kind,
		arg.RootPath,
		arg.DisplayName,
		arg.ID,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RootPath,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO sources (kind, root_path, display_name)
VALUES (?, ?, ?)
ON CONFLICT(kind, root_path) DO UPDATE SET
    display_name = excluded.display_name,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, kind, root_path, display_name, created_at, updated_at
`

type UpsertSourceParams struct {
	Kind        string         `json:"kind"`
	RootPath    string         `json:"root_path"`
	DisplayName sql.NullString `json:"display_name"`
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, upsertSource, arg.Kind, arg.RootPath, arg.DisplayName)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RootPath,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSourceFile = `-- name: UpsertSourceFile :one
INSERT INTO source_files (
    source_id, project_id, path, kind, size_bytes, mtime_unix, sha256, indexed_at, parser_version
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(source_id, path) DO UPDATE SET
    project_id = excluded.project_id,
    kind = excluded.kind,
    size_bytes = excluded.size_bytes,
    mtime_unix = excluded.mtime_unix,
    sha256 = excluded.sha256,
    indexed_at = excluded.indexed_at,
    parser_version = excluded.parser_version
RETURNING id, source_id, project_id, path, kind, size_bytes, mtime_unix, sha256, indexed_at, parser_version
`

type UpsertSourceFileParams struct {
	SourceID      int64          `json:"source_id"`
	ProjectID     sql.NullInt64  `json:"project_id"`
	Path          string         `json:"path"`
	Kind          string         `json:"kind"`
	SizeBytes     sql.NullInt64  `json:"size_bytes"`
	MtimeUnix     sql.NullInt64  `json:"mtime_unix"`
	Sha256        sql.NullString `json:"sha256"`
	IndexedAt     sql.NullString `json:"indexed_at"`
	ParserVersion string         `json:"parser_version"`
}

func (q *Queries) UpsertSourceFile(ctx context.Context, arg UpsertSourceFileParams) (SourceFile, error) {
	row := q.db.QueryRowContext(ctx, upsertSourceFile,
		arg.SourceID,
		arg.ProjectID,
		arg.Path,
		arg.Kind,
		arg.SizeBytes,
		arg.MtimeUnix,
		arg.Sha256,
		arg.IndexedAt,
		arg.ParserVersion,
	)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.Sha256,
		&i.IndexedAt,
		&i.ParserVersion,
	)
	return i, err
}
