// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
)

const getIndexStats = `-- name: GetIndexStats :one
SELECT
    (SELECT count(*) FROM projects) AS project_count,
    (SELECT count(*) FROM conversations) AS conversation_count,
    (SELECT count(*) FROM messages) AS message_count,
    (SELECT count(*) FROM source_files) AS source_file_count,
    (SELECT coalesce(max(indexed_at), '') FROM source_files) AS last_indexed_at
`

type GetIndexStatsRow struct {
	ProjectCount      int64       `json:"project_count"`
	ConversationCount int64       `json:"conversation_count"`
	MessageCount      int64       `json:"message_count"`
	SourceFileCount   int64       `json:"source_file_count"`
	LastIndexedAt     interface{} `json:"last_indexed_at"`
}

func (q *Queries) GetIndexStats(ctx context.Context) (GetIndexStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getIndexStats)
	var i GetIndexStatsRow
	err := row.Scan(
		&i.ProjectCount,
		&i.ConversationCount,
		&i.MessageCount,
		&i.SourceFileCount,
		&i.LastIndexedAt,
	)
	return i, err
}
