// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
)

const getIndexStats = `-- name: GetIndexStats :one
SELECT
    (SELECT count(*) FROM projects) AS project_count,
    (SELECT count(*) FROM conversations) AS conversation_count,
    (SELECT count(*) FROM messages) AS message_count,
    (SELECT count(*) FROM source_files) AS source_file_count,
    (SELECT coalesce(max(indexed_at), '') FROM source_files) AS last_indexed_at
`

type GetIndexStatsRow struct {
	ProjectCount      int64       `json:"project_count"`
	ConversationCount int64       `json:"conversation_count"`
	MessageCount      int64       `json:"message_count"`
	SourceFileCount   int64       `json:"source_file_count"`
	LastIndexedAt     interface{} `json:"last_indexed_at"`
}

func (q *Queries) GetIndexStats(ctx context.Context) (GetIndexStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getIndexStats)
	var i GetIndexStatsRow
	err := row.Scan(
		&i.ProjectCount,
		&i.ConversationCount,
		&i.MessageCount,
		&i.SourceFileCount,
		&i.LastIndexedAt,
	)
	return i, err
}

const listProjectSummaries = `-- name: ListProjectSummaries :many
WITH project_conversations AS (
    SELECT p.id AS project_id, c.id AS conversation_id
    FROM projects p
    JOIN conversations c ON c.project_id = p.id
    UNION
    SELECT p.id AS project_id, c.id AS conversation_id
    FROM projects p
    JOIN tool_calls tc
      ON p.canonical_path IS NOT NULL
     AND (
        tc.working_directory = p.canonical_path
        OR tc.working_directory LIKE p.canonical_path || '/%'
     )
    JOIN messages m ON m.id = tc.message_id
    JOIN conversations c ON c.id = m.conversation_id
    UNION
    SELECT p.id AS project_id, c.id AS conversation_id
    FROM projects p
    JOIN files f
      ON p.canonical_path IS NOT NULL
     AND (
        coalesce(f.normalized_path, f.path) = p.canonical_path
        OR coalesce(f.normalized_path, f.path) LIKE p.canonical_path || '/%'
     )
    JOIN file_mentions fm ON fm.file_id = f.id
    JOIN messages m ON m.id = fm.message_id
    JOIN conversations c ON c.id = m.conversation_id
)
SELECT
    p.slug AS project_slug,
    coalesce(p.name, p.slug) AS project_name,
    coalesce(p.canonical_path, p.git_root, '') AS project_dir,
    count(DISTINCT pc.conversation_id) AS chats
FROM projects p
LEFT JOIN project_conversations pc ON pc.project_id = p.id
GROUP BY p.id
ORDER BY project_name
`

type ListProjectSummariesRow struct {
	ProjectSlug string `json:"project_slug"`
	ProjectName string `json:"project_name"`
	ProjectDir  string `json:"project_dir"`
	Chats       int64  `json:"chats"`
}

func (q *Queries) ListProjectSummaries(ctx context.Context) ([]ListProjectSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectSummariesRow{}
	for rows.Next() {
		var i ListProjectSummariesRow
		if err := rows.Scan(
			&i.ProjectSlug,
			&i.ProjectName,
			&i.ProjectDir,
			&i.Chats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
